version: '2.1'

services:
  backend_postgres:
    image: postgres:11-alpine
    restart: always
    ports: 
      - 5432:5432
    networks:
      - database_net
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment:
      POSTGRES_PASSWORD: "pe5Cador"

  backend_postgres_admin:
    image: adminer
    restart: always
    ports:
      - 8086:8080
    networks:
      - database_net
    environment:
      ADMINER_DEFAULT_DRIVER: "pgsql"
      ADMINER_DEFAULT_SERVER: "backend_postgres"
      ADMINER_DEFAULT_USERNAME: "postgres"
      ADMINER_DEFAULT_PASSWORD: "pe5Cador"
      ADMINER_DEFAULT_DB: "postgres"

  backend:
    image: maven:3.5-jdk-8
    command: mvn clean spring-boot:run -Dmaven.clean.failOnError=false
    working_dir: /usr/src/app
    restart: always
    ports:
      - 8085:8080
    networks:
      - database_net
      - backend_net
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/.m2:/usr/src/app/.m2
      - ./backend/pom.xml:/usr/src/app/pom.xml
      - ./backend/application.yml:/usr/src/app/application.yml
      - m2:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: "postgres"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://backend_postgres:5432/postgres"
      SPRING_DATASOURCE_PASSWORD: "pe5Cador"
  
  frontend:
    build: ./frontend
    command: npm start
    working_dir: /usr/src/app
    restart: always
    ports:
      - 8084:3000
    networks:
      - backend_net
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/package.json:/usr/src/app/package.json
      - ./frontend/public:/usr/src/app/public
      - ./frontend/static:/usr/src/app/static
    environment:
      REACT_APP_API_URL: "http://backend:8080/api/v1"

networks:
  database_net:
  backend_net:

volumes:
  postgres_data:
    name: postgres_data
  m2:
    name: m2
