version: '2.1'

services:
  backend_postgres:
    image: postgres:11-alpine
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment:
      POSTGRES_PASSWORD: "pe5Cador"

  backend_postgres_admin:
    image: adminer
    restart: always
    ports:
      - 8086:8080
    environment:
      ADMINER_DEFAULT_DRIVER: "pgsql"
      ADMINER_DEFAULT_SERVER: "backend_postgres"
      ADMINER_DEFAULT_USERNAME: "postgres"
      ADMINER_DEFAULT_PASSWORD: "pe5Cador"
      ADMINER_DEFAULT_DB: "postgres"

  backend:
    image: maven:3.5-jdk-8
    command: mvn clean spring-boot:run -Dmaven.clean.failOnError=false
    command: mvn --settings .m2/settings.xml clean spring-boot:run -Dmaven.clean.failOnError=false
    working_dir: /usr/src/app
    restart: always
    ports:
      - 8085:8080
    volumes:
      - ./src:/usr/src/app/src
      - ./.m2:/usr/src/app/.m2
      - ./pom.xml:/usr/src/app/pom.xml
      - m2:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: "postgres"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://backend_postgres:5432/postgres"
      SPRING_DATASOURCE_PASSWORD: "pe5Cador"

volumes:
  postgres_data:
    name: postgres_data
  m2:
    name: m2
